# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stale_fish}
  s.version = "1.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Smestad"]
  s.date = %q{2009-10-03}
  s.email = %q{justin.smestad@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/stale_fish.rb",
     "lib/stale_fish/fakeweb.rb",
     "lib/stale_fish/fixture_definition.rb",
     "lib/stale_fish/utility.rb",
     "spec/deprecation_spec.rb",
     "spec/fixtures/deprecated_yaml.yml",
     "spec/fixtures/google.html",
     "spec/fixtures/malformed_stale_fish.yml",
     "spec/fixtures/stale_fish.yml",
     "spec/fixtures/stale_fish_fakeweb.yml",
     "spec/fixtures/yahoo.html",
     "spec/spec_helper.rb",
     "spec/stale_fish_spec.rb",
     "stale_fish.gemspec",
     "tmp/.gitignore"
  ]
  s.homepage = %q{http://github.com/jsmestad/stale_fish}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{keeps fixtures synchronized with sources to prevent outdated fixtures going undetected.}
  s.test_files = [
    "spec/deprecation_spec.rb",
     "spec/spec_helper.rb",
     "spec/stale_fish_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<facets>, [">= 0"])
      s.add_runtime_dependency(%q<fakeweb>, [">= 1.2.4"])
      s.add_runtime_dependency(%q<resourceful>, ["~> 0.6.1"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.1.2"])
    else
      s.add_dependency(%q<facets>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.4"])
      s.add_dependency(%q<resourceful>, ["~> 0.6.1"])
      s.add_dependency(%q<activesupport>, [">= 2.1.2"])
    end
  else
    s.add_dependency(%q<facets>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.4"])
    s.add_dependency(%q<resourceful>, ["~> 0.6.1"])
    s.add_dependency(%q<activesupport>, [">= 2.1.2"])
  end
end
